<?php

namespace com\hartwick;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-11 at 15:01:57.
 */
class autodiscoverTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var autodiscover
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new autodiscover;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers com\hartwick\autodiscover::setHost
	 * @todo   Implement testSetHost().
	 */
	public function testSetHost() {
		$this->object->setHost(gethostname());
		$this->assertEquals(gethostname(), $this->object->getHost());
	}

	/**
	 * @covers com\hartwick\autodiscover::setSRV
	 * @todo   Implement testSetSRV().
	 */
	public function testSetSRV() {
		$this->object->setHost("_submission");
		$this->assertEquals("_submission", $this->object->getSRV());
	}

	/**
	 * @covers com\hartwick\autodiscover::setProto
	 * @todo   Implement testSetProto().
	 */
	public function testSetProto() {
		$this->object->setHost("_tcp");
		$this->assertEquals("_tcp", $this->object->getProto());
	}

	/**
	 * @covers com\hartwick\autodiscover::getHost
	 * @todo   Implement testGetHost().
	 */
	public function testGetHost() {
		$this->object->setHost("www.hartwick.com");
		$this->assertEquals("www.hartwick.com", $this->object->getHost());
	}

	/**
	 * @covers com\hartwick\autodiscover::getSRV
	 * @todo   Implement testGetSRV().
	 */
	public function testGetSRV() {
		$this->object->setHost("_submission");
		$this->assertEquals("_submission", $this->object->getSRV());
	}

	/**
	 * @covers com\hartwick\autodiscover::getProto
	 * @todo   Implement testGetProto().
	 */
	public function testGetProto() {
		$this->object->setHost("_tcp");
		$this->assertEquals("_tcp", $this->object->getProto());
	}

	public function testCheckRR() {
		$this->object->setHost("www.hartwick.com");
		$returned = $this->object->CheckRR();
		$this->assertEquals(array('outgoing1.hartwick.com', 587), $returned);
	}
}
