<?php
/* 
 * Copyright (C) 2016 Michael J. Hartwick <hartwick at hartwick.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
namespace com\hartwick;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-05 at 19:06:46.
 */
class ColourTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Colour
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Colour("RGB(127, 0, 255)");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

		public function testConstructorRGB() {
      $object = new Colour("rgb(127, 0, 255)");
			$this->assertEquals("rgb", $object->format);
		}
		
		public function testConstructorArray() {
			$object = new Colour(array('r' => 127, 'g' => 0, 'b' => 255));
			$this->assertEquals("array", $object->format);
		}
		
		public function testConstructorHex() {
			$object = new Colour("#7f00ff");
			$this->assertEquals("hex", $object->format);
		}
		
    /**
     * @covers com\hartwick\Colour::getHex
     */
    public function testGetHex() {
				$a = new Colour("rgb(127, 0, 255)");
        $this->assertEquals("#7F00FF", $a->getHex());
    }
		
    /**
     * @covers com\hartwick\Colour::getHSL
     */
		public function testGetHSL() {
			$a = new Colour("#7f00ff");
			$this->assertEquals(array(0.7497, 1, 0.5), $a->getHSL());
		}
		
    /**
     * @covers com\hartwick\Colour::complementary
     */
		public function testcomplementary() {
			$a = new Colour("#7f00ff");
			$this->assertEquals(array(0.2497, 1, 0.5), $a->complementary());
		}

}
