<?php
namespace com\hartwick;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-04 at 17:05:11.
 */
class dnscheckTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var dnscheck
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new dnscheck;
				$this->object->setDomain("hartwick.com");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers com\hartwick\dnscheck::setDomain
     */
    public function testSetDomain()
    {
			$returned = $this->object->setDomain("hartwickservices.com");
			$this->assertEquals("hartwickservices.com", $returned);
    }

    /**
     * @covers com\hartwick\dnscheck::getDomain
     */
    public function testGetDomain()
    {
			$returned = $this->object->getDomain();
			$this->assertEquals("hartwick.com", $returned);
    }

    /**
     * @covers com\hartwick\dnscheck::checkDelegation
     */
    public function testCheckDelegation()
    {
			$returned = $this->object->checkDelegation();
			$this->assertEquals(\TRUE, $returned);
    }

		/**
     * @covers com\hartwick\dnscheck::checkDomain
     */
    public function testCheckDomain()
    {
			$this->object->checkDelegation();
			$returned = $this->object->checkDomain();
			$this->assertEquals(\TRUE, $returned);
    }

		/**
     * @covers com\hartwick\dnscheck::nagiosOutput
     */
    public function testnagiosOutput()
    {
			$this->object->checkDelegation();
			$this->object->checkDomain();
			$returned = $this->object->nagiosOutput();
			$this->assertEquals("OK: Tested 4", $returned);
    }

		
}
